server:
  port: 8085
hm:
  db:
    database: hm-trade
  swagger:
    tittle: 黑马商城交易服务接口文档
    desc: "黑马商城交易服务接口文档"
    basepackage: com.hmall.trade.controller
spring:
  rabbitmq:
    host: 192.168.115.132
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: hmall
