server:
  port: 8084
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
  db:
    database: hm-user
  swagger:
    tittle: 黑马商城用户服务接口文档
    desc: "黑马商城用户服务接口文档"
    basepackage: com.hmall.user.controller
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true