server:
  port: 8081

hm:
  db:
    database: hm-item
  swagger:
    tittle: 黑马商城商品服务接口文档
    desc: "黑马商城商品服务接口文档"
    basepackage: com.hmall.item.controller
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090   # 指定sentinel控制台地址
      http-method-specify: true    # 开启sentinel对http method的校验